"""fix date bug

Revision ID: 43ef2034d24a
Revises: 
Create Date: 2026-07-24 12:54:07.810547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ef2034d24a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('excluded_keywords', sa.JSON(), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('min_relevance_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('agent_result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_status'), 'search_runs', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_form_url', sa.String(length=500), nullable=True),
    sa.Column('vk_url', sa.String(length=500), nullable=True),
    sa.Column('telegram_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('rutube_url', sa.String(length=500), nullable=True),
    sa.Column('dzen_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recipient_address', sa.String(length=500), nullable=True),
    sa.Column('recipient_external_id', sa.String(length=255), nullable=True),
    sa.Column('generated_message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_search_run_id'), 'contacts', ['search_run_id'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_contact_id'), 'communications', ['contact_id'], unique=False)
    op.create_index(op.f('ix_communications_status'), 'communications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communications_status'), table_name='communications')
    op.drop_index(op.f('ix_communications_contact_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_contacts_search_run_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_search_runs_status'), table_name='search_runs')
    op.drop_table('search_runs')
    # ### end Alembic commands ###
